spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: shop-udea-ui
zuul:
  ignored-services: '*'
  routes:
    catalog-service:
      path: /api/catalog/**
      url: http://127.0.0.1:9999
    order-service:
      path: /api/order/**
      url: http://127.0.0.1:8888
    auth-service:
      path: /user/**
      url: http://127.0.0.1:8181/uaa/user
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://127.0.0.1:8181/uaa/user
    client:
      accessTokenUri: http://127.0.0.1:8181/uaa/oauth/token
      userAuthorizationUri: http://127.0.0.1:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: shop-udea-ui
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://${DOCKER_IP:127.0.0.1}:9999
    auth-service:
      path: /user/**
      url: http://${DOCKER_IP:127.0.0.1}:8181/uaa/user
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:127.0.0.1}:8181/uaa/user
    client:
      accessTokenUri: http://${DOCKER_IP:127.0.0.1}:8181/uaa/oauth/token
      userAuthorizationUri: http://${DOCKER_IP:127.0.0.1}:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret